project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "David Hein"
  description: "Data Scientist at UT Southwestern — AI, MLOps, and oncology research."
  navbar:
    right:
      - projects.qmd
      - index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/DavidHein96
      - icon: linkedin
        href: https://linkedin.com/in/david-hein-utsw

    
format:
  html:
    theme: minty
    css: styles.css
    grid:
     sidebar-width: 275px
     body-width: 1000px
     margin-width: 275px
     gutter-width: 1.5rem
    code-block-border-left: "#78c2ad"
    code-block-bg: true
    highlight-style: kate

editor: visual

