project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "Dave's Site"
  navbar:
    right:
      - projects.qmd
      - index.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin 
        href: https://linkedin.com/in/david-h-a37220179
#- icon: linkedin
#      text: LinkedIn
#      href: https://linkedin.com
  #sidebar:
  #  contents: auto
  #  style: floating
    
format:
  html:
    theme: minty
    fontsize: 1.4em
    css: styles.css
    #page-layout: full
    grid: 
     sidebar-width: 340px
     body-width: 1400px
     margin-width: 450px
     gutter-width: 1.5rem
    code-block-border-left: "#78c2ad"
    code-block-bg: true
    highlight-style: kate

editor: visual

